FROM mysql:latest

ENV MYSQL_ROOT_PASSWORD=root

# initalize database
COPY dbchat/assets/1-init.sql /docker-entrypoint-initdb.d/
COPY dbchat/assets/2-sakila-schema.sql /docker-entrypoint-initdb.d/
COPY dbchat/assets/3-sakila-data.sql /docker-entrypoint-initdb.d/


EXPOSE 3306
