version: '3.8'

services:
  mysql-container:
    image: dbchatcr.azurecr.io/dbchat-db
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  dbchat-backend:
    image: dbchatcr.azurecr.io/dbchat-backend
    container_name: dbchat-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: mysql-container
      MYSQL_PORT: "3306"
      MYSQL_USER: newuser
      MYSQL_PASSWORD: 
      MYSQL_UPASSWORD: 
      MYSQL_DB: sakila
      ALLOWED_DBS: sakila
      OPENAI_API_KEY: 
      AWS_ACCESS_KEY_ID:
      AWS_REGION: "us-west-2"
      AWS_SECRET_ACCESS_KEY: 
    ports:
      - "8000:8000"
    depends_on:
      mysql-container:
        condition: service_healthy

